server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ApiModule
          uri: lb://TRAFFIC-CONTROL-API
          predicates:
            - Path=/traffic-control/**
        - id: ServiceModule
          uri: lb://FLIGHT-PLANNER-SERVICE
          predicates:
            - Path=/flight-planner/**